export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { createServiceClient } from '@/lib/supabase/service'
import { format } from 'date-fns'
import { generatePreMarketBrief } from '@/lib/pre-market-brief'

function validateSecret(request: NextRequest): boolean {
  const expected = process.env.JOURNAL_AUTO_SECRET || ''
  if (!expected) return false
  const auth = request.headers.get('authorization') || ''
  const bearer = auth.replace(/^Bearer\s+/i, '').trim()
  const xSecret = request.headers.get('x-journal-secret') || ''
  return bearer === expected || xSecret === expected
}

export async function OPTIONS() {
  return new Response(null, { status: 200 })
}

export async function POST(request: NextRequest) {
  if (!validateSecret(request)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  let body: { brief?: unknown; scheduledTime?: unknown }
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const { brief, scheduledTime } = body

  if (!brief || typeof brief !== 'string') {
    return NextResponse.json({ error: 'brief (string) is required' }, { status: 400 })
  }

  const supabase = createServiceClient()
  const today = format(new Date(), 'yyyy-MM-dd')

  const { data: profiles } = await supabase.from('profiles').select('id').limit(1)
  const userId = profiles?.[0]?.id
  if (!userId) {
    return NextResponse.json({ error: 'No user profile found' }, { status: 500 })
  }

  const { error: upsertError } = await supabase
    .from('daily_briefs')
    .upsert(
      { user_id: userId, date: today, brief_text: brief },
      { onConflict: 'user_id,date' }
    )

  if (upsertError) {
    return NextResponse.json(
      { error: `DB error: ${upsertError.message}` },
      { status: 500 }
    )
  }

  // Auto-generate a baseline AI brief from the imported text (Option B).
  // Guards: only when no brief exists yet for today (never clobber a brief the
  // trader generated by hand, and skip the redundant later post of the day).
  // Best-effort: an AI/parse failure must never fail the text import above.
  let autoGenerated = false
  try {
    const { data: session } = await supabase
      .from('daily_sessions')
      .select('id, pre_market_brief')
      .eq('user_id', userId)
      .eq('date', today)
      .maybeSingle()

    if (!session?.pre_market_brief) {
      const aiBrief = await generatePreMarketBrief(brief)
      if (aiBrief) {
        if (session) {
          await supabase
            .from('daily_sessions')
            .update({ pre_market_brief: aiBrief })
            .eq('id', session.id)
        } else {
          await supabase
            .from('daily_sessions')
            .insert({ user_id: userId, date: today, pre_market_brief: aiBrief })
        }
        autoGenerated = true
      }
    }
  } catch (genErr) {
    console.error(
      'Auto-generate pre-market brief failed (non-fatal):',
      genErr instanceof Error ? genErr.message : genErr
    )
  }

  return NextResponse.json({
    success: true,
    date: today,
    autoGenerated,
    scheduledTime: scheduledTime ?? null,
  })
}
